import { AttributeComponentIds } from "../enums";

export const LF32_MAX = 3.402_823_466e+38;
export const DEFAULT_ATTRIBUTES = {
	[AttributeComponentIds.Absorption]:{
		name: AttributeComponentIds.Absorption,
		min: 0,
		max: 16,
		default: 0,
		current: 0,
		modifiers: []
	},
	[AttributeComponentIds.PlayerSaturation]:{
		name: AttributeComponentIds.PlayerSaturation,
		min: 0,
		max: 20,
		default: 5,
		current: 5,
		modifiers: [],
	},
	[AttributeComponentIds.PlayerExhaustion]:{
		name: AttributeComponentIds.PlayerExhaustion,
		min: 0,
		max: 20,
		default: 0,
		current: 0,
		modifiers: [],
	},
	[AttributeComponentIds.KnockbackResistence]:{
		name: AttributeComponentIds.KnockbackResistence,
		min: 0,
		max: 1,
		default: 0,
		current: 0,
		modifiers: [],
	},
	[AttributeComponentIds.Health]:{
		name: AttributeComponentIds.Health,
		min: 0,
		max: 20,
		default: 20,
		current: 20,
		modifiers: [],
	},
	[AttributeComponentIds.Movement]:{
		name: AttributeComponentIds.Movement,
		min: 0,
		max: LF32_MAX,
		default: 0.1,
		current: 0.1,
		modifiers: [],
	},
	[AttributeComponentIds.FollowRange]:{
		name: AttributeComponentIds.FollowRange,
		min: 0,
		max: 2_048,
		default: 16,
		current: 16,
		modifiers: [],
	},
	[AttributeComponentIds.PlayerHunger]:{
		name: AttributeComponentIds.PlayerHunger,
		min: 0,
		max: 20,
		default: 20,
		current: 0,
		modifiers: [],
	},
	[AttributeComponentIds.AttackDamage]:{
		name: AttributeComponentIds.AttackDamage,
		min: 0,
		max: 1,
		default: 1,
		current: 1,
		modifiers: [],
	},
	[AttributeComponentIds.PlayerExperience]:{
		name: AttributeComponentIds.PlayerExperience,
		min: 0,
		max: 1,
		default: 0,
		current: 0,
		modifiers: [],
	},
	[AttributeComponentIds.PlayerLevel]:{
		name: AttributeComponentIds.PlayerLevel,
		min: 0,
		max: 24_791,
		default: 0,
		current: 744,
		modifiers: [],
	},
	[AttributeComponentIds.UnderwaterMovement]:{
		name: AttributeComponentIds.UnderwaterMovement,
		min: 0,
		max: LF32_MAX,
		default: 0.02,
		current: 0.02,
		modifiers: [],
	},
	[AttributeComponentIds.Luck]:{
		name: AttributeComponentIds.Luck,
		min: -1_024,
		max: 1_024,
		default: 0,
		current: 0,
		modifiers: [],
	},
	[AttributeComponentIds.FallDamage]:{
		name: AttributeComponentIds.FallDamage,
		min: 0,
		max: LF32_MAX,
		default: 1,
		current: 1,
		modifiers: [],
	},
	[AttributeComponentIds.HorseJumpStrength]:{
		name: AttributeComponentIds.HorseJumpStrength,
		min: 0,
		max: 2,
		default: 0.7,
		current: 0.7,
		modifiers: [],
	},
	[AttributeComponentIds.ZombieSpawnReinforcements]:{
		name: AttributeComponentIds.ZombieSpawnReinforcements,
		min: 0,
		max: 1,
		default: 0,
		current: 0,
		modifiers: [],
	},
	[AttributeComponentIds.LavaMovement]:{
		name: AttributeComponentIds.LavaMovement,
		min: 0,
		max: LF32_MAX,
		default: 0.02,
		current: 0.02,
		modifiers: [],
	}
};
