export {
	EntityComponentId, AbsorptionComponent, AttackDamageComponent, FallDamageComponent,
	FollowRangeComponent, HealthComponent, HorseJumpStrengthComponent, KnockbackResistenceComponent, LavaMovementComponent,
	LuckComponent, MovementComponent, PlayerExhaustionComponent,PlayerExperienceComponent,PlayerHungerComponent,PlayerLevelComponent,
	PlayerSaturationComponent, ScaleComponent,StatusPropertiesComponent,UnderwaterMovementComponent,ZombieSpawnReinforcementsComponent
} from "./EntityComponents.js";
